var http = require('http');
var url = require('url');
var axios = require('axios');
var fs = require('fs');

function genOcorrenciasFilmes(ocorrencias){
    pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Filmes</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">

            <header class="w3-container w3-teal">
                <h1>Filmes</h1>
            </header>
            
            <div class="w3-container">
                <table class="w3-table w3-striped">
                    <tr>
                        <th>Identificador</th>
                        <th>Título</th>
                        <th>Ano</th>
                        <th>Elenco</th>
                        <th>Gêneros</th>
                    </tr>
    `
    ocorrencias.forEach( ocorr => {
        pagHTML += `
        <tr>
            <td>${ocorr.id}</td>
            <td>${ocorr.title}</td>
            <td>${ocorr.year}</td>
            <td>${ocorr.cast}</td>
            <td>${ocorr.genres}</td>
        </tr>
        `
    });
    pagHTML += `
    </table>
        </div>
            
            <footer class="w3-container w3-teal">
                <h5>Generated by Afonso Silva</h5>
            </footer>
            
        </div>
    </body>
</html>
    `
    return pagHTML
}
function genOcorrenciaFilme(dataFilme){
    pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>${dataFilme.title}</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">

            <header class="w3-container w3-teal">
                <h1>${dataFilme.title}</h1>
            </header>
            
            <div class="w3-container">
                <p><b>Ano de Lançamento:</b> ${dataFilme.year}</p>
                <p><b>Elenco: </b> `
                if (dataFilme.cast != null){
                    dataFilme.cast.forEach( (ator) => {
                        pagHTML += `<a href='cast/${ator}> ${ator} |</a'`;
                    })
                } else {
                    pagHTML += "N/A";
                }
                `</p>
                <p><b>Gênero: </b> `
                if (dataFilme.genre != null){
                    dataFilme.genre.forEach( (genre) => {
                        pagHTML += `<a href='cast/${genre}> ${genre} |</a'`;
                    })
                } else {
                    pagHTML += "N/A";
                }
                `</p>
            </div>
            
            <footer class="w3-container w3-teal">
                <h5>Generated by Afonso Silva</h5>
            </footer>
            
        </div>
    </body>
</html>
    `
    return pagHTML
}

http.createServer((req, res) => {
    console.log(req.method + " " + req.url);

    if (req.url == '/'){
        
    } else if (req.url == '/w3.css') {
        fs.readFile('w3.css', (err, dados) => {
            res.writeHead(200, {'Content-Type': 'text/css; charset=utf-8'});
            res.write(dados);
            res.end();
        });
    } else if (req.url == '/filmes') {
        axios.get("http://localhost:3000/movies")
            .then((response) => {
                res.writeHead(200, {'Content-Type': 'text/html; charset=utf-8'});
                data = response.data;
                htmlString = genOcorrenciasFilmes(data);
                res.write(htmlString);
                res.end();
            })
            .catch((erro) => {
                res.writeHead(500, {'Content-Type': 'text/html; charset=utf-8'});
                res.write("<p>Ocorreu um erro: " + erro + "</p>");
                res.end();
            });
    } else if (req.url.match(/\/filmes\/([a-z]|[A-Z]|[0-9])+/)) { // TODO: Adicionar ID do filme
        let idMovie = req.url.substring(8)
        axios.get("http://localhost:3000/movies/" + idMovie)
            .then((response) => {
                res.writeHead(200, {'Content-Type': 'text/html; charset=utf-8'});
                data = response.data;
                htmlString = genOcorrenciaFilme(data);
                res.write(htmlString);
                res.end();
            })
            .catch((erro) => {
                res.writeHead(500, {'Content-Type': 'text/html; charset=utf-8'});
                res.write("<p>Ocorreu um erro: " + erro + "</p>");
                res.end();
            });
    } else {
        res.writeHead(400, {'Content-Type': 'text/html; charset=utf-8'});
        res.write("<p>Erro: Pedido não encontrado</p>");
        res.write("<pre>" + req.url + "</pre>");
        res.end();
    }

}).listen(2702);

console.log("Servidor à escuta na porta 2702..") 