exports.writersListPage = function(writers) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de Compositores
                    <a class="w3-btn w3-round w3-blue" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Nome</th>
                            <th>Biografia</th>
                            <th>Data de Nascimento</th>
                            <th>Data de Óbito</th>
                            <th>Período</th>
                            <th>Ações</th>
                        </tr>
                `
    for(let i=0; i < writers.length ; i++){
        pagHTML += `
                <tr>
                    <td>
                        <a href="/compositores/${writers[i].id}">
                            ${writers[i].nome}
                        </a>
                    </td>
                    <td>${writers[i].bio}</td>
                    <td>${writers[i].dataNasc}</td>
                    <td>${writers[i].dataObito}</td>
                    <td><a href="/periodos/${writers[i].periodo}">
                            ${writers[i].periodo}
                        </a>
                    </td>
                    <td>
                        [<a href="/compositores/edit/${writers[i].id}">Edit</a>]
                        [<a href="/compositores/delete/${writers[i].id}">Delete</a>]
                    </td>
                </tr>\
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by Afonso Silva, 10th March 2024</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.writerPage = function(writer){
    var pagHTML = `
    <html>
    <head>
        <title>${writer.nome}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${writer.nome}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:80%">
                    <li><b>Nome: </b>${writer.nome}</li>
                    <li><b>Biografia: </b>${writer.bio}</li>
                    <li><b>Data de Nascimento: </b>${writer.dataNasc}</li>
                    <li><b>Data de Óbito: </b>${writer.dataObito}</li>
                    <li><b>Período: </b> <a href="/periodos/${writer.periodo}">${writer.periodo}</a></li>
                </ul>
            </div>`
    

    pagHTML +=     `
            <footer class="w3-container w3-teal">
                <address>Gerado por Afonso Silva, 10th March 2024 - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

exports.periodsListPage = function(periods) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Períodos</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de Períodos
                    <a class="w3-btn w3-round w3-blue" href="/periodos/registo">+</a>
                    </h1>
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Ações</th>
                        </tr>
                `
    for(let i=0; i < periods.length ; i++){
        pagHTML += `
                <tr>
                    <td>${periods[i].id}</td>
                    <td>
                        <a href="/periodos/${periods[i].nome}">
                            ${periods[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/periodos/edit/${periods[i].id}">Edit</a>]
                        [<a href="/periodos/delete/${periods[i].id}">Delete</a>]
                    </td>
                </tr>\
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by Afonso Silva, 10th March 2024</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodPage = function(period, writers){
    var pagHTML = `
    <html>
    <head>
        <title>${period}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositores do período ${period}</h1>
            </header>

            <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Nome</th>
                            <th>Data de Nascimento</th>
                            <th>Data de Óbito</th>
                        </tr>
                `
    for(let i=0; i < writers.length ; i++){
        pagHTML += `
                <tr>
                    <td>
                        <a href="/compositores/${writers[i].id}">
                            ${writers[i].nome}
                        </a>
                    </td>
                    <td>${writers[i].dataNasc}</td>
                    <td>${writers[i].dataObito}</td>
                </tr>\
        `
    }

    pagHTML += `
            </table>
            <footer class="w3-container w3-teal">
                <address>Gerado por Afonso Silva, 10th March 2024 - [<a href="/periodos">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

exports.addWriterFormPage = function(){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Adicionar compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Formulário do compositor</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" required/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" required/>
                        <label>Biografia</label>
                        <input class="w3-input w3-round" type="text" name="bio" />
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc" required/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo" required/>
                    </fieldset>

                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Registar</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by Afonso Silva, 10th March 2024 - [<a href="/compositores">Voltar</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.editWriterFormPage = function(writer){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Editar compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Formulário do compositor</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${writer.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${writer.nome}"/>
                        <label>Biografia</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${writer.bio}"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc" value="${writer.dataNasc}"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito" value="${writer.dataObito}"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${writer.periodo}"/>
                    </fieldset>

                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Editar</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by Afonso Silva, 10th March 2024 - [<a href="/compositores">Voltar</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

exports.addPeriodFormPage = function(){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Adicionar período</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Formulário do período</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" required/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" required/>
                    </fieldset>

                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Registar</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by Afonso Silva, 10th March 2024 - [<a href="/periodos">Voltar</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.editPeriodFormPage = function(period){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Editar compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Formulário do compositor</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${period.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${period.nome}"/>
                    </fieldset>

                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Editar</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by Afonso Silva, 10th March 2024 - [<a href="/periodos">Voltar</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}